apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor-default-plugins
  namespace: system
  labels:
    plugin: executor-default-plugins
spec:
  selector:
    matchLabels:
      plugin: executor-default-plugins
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: executor-default-plugins
      labels:
        plugin: executor-default-plugins
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /executor-default-plugins
        image: kubearbiter/executor-default-plugins:v0.2.0
        name: executor-default-plugins
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: executor
      terminationGracePeriodSeconds: 10
